server:
  port: 8881

spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          name: ${spring.application.name}
          service-base-url: http://localhost:${server.port}
        monitor:
          period: 100000
          status-lifetime: 100000
          connect-timeout: 100000
          read-timeout: 100000
  application:
    name: Ares-GateWay
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ares_system
          uri: lb://Ares-System
          predicates:
            - Path=/ares/**
        - id: ares_cache
          uri: lb://Ares-Cache
          predicates:
            - Path=/cache/**
        - id: ares_quartz
          uri: lb://Ares-Quartz
          predicates:
            - Path=/quartz/**

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'


info:
  project-name: ${spring.application.name}
  project-author: yy
  project-description: ${spring.application.name} project


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8880/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
